version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    environment:
      PORT: "8080"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
    ports:
      - "8080:8080"
