FROM python:3-slim AS build
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install pip-tools
RUN pip-sync requirements.txt --pip-args '--target /packages'

# Copy application
COPY accountant accountant
COPY worker.py .

# Build production image
FROM gcr.io/distroless/python3-debian10
COPY --from=build /packages /packages
COPY --from=build /app /app

WORKDIR /app
ENV PYTHONPATH /packages
CMD ["worker.py"]
